In [49]:
import optax
import matplotlib.pyplot as plt
import numpy as np
import jax
import jax.numpy as jnp

x = jnp.array(np.random.randn(500, 200))
b2 = 0

# automatic
opt = optax.scale_by_adam(b1=0, b2=b2)
opt_state = opt.init(x)

# manual
nu = jnp.zeros_like(x)

def loss(_x): return (_x * _x).sum() ** 0.5
errs = []
for _ in range(1000):
    grads = jax.grad(loss)(x)

    g_auto, opt_state = opt.update(grads, opt_state)

    nu = b2 * nu + (1 - b2) * (grads ** 2)
    g_manual = grads / (nu ** 0.5)

    error = jnp.linalg.norm(g_auto - g_manual)
    print(g_auto)
    print(g_manual)
    print()
    break
    errs.append(error)
# plt.plot(range(len(errs)), errs)

[[ 0.9999972   0.9999984   0.9999928  ...  0.99999154 -0.9999979
   0.9999984 ]
 [ 0.9999944   0.9999962  -0.99999875 ...  0.9999359  -0.999998
  -0.99999326]
 [ 0.99999154  0.99999774 -0.9999925  ...  0.99999607 -0.99999714
  -0.9999989 ]
 ...
 [-0.9999966   0.9999927  -0.9999974  ... -0.9999951  -0.9999941
   0.99999774]
 [-0.99999803 -0.99999654  0.9999914  ... -0.9999981   0.9999939
  -0.9999802 ]
 [-0.9999955  -0.9999966  -0.9999978  ...  0.9999968  -0.99999505
   0.9999965 ]]
[[ 1.  1.  1. ...  1. -1.  1.]
 [ 1.  1. -1. ...  1. -1. -1.]
 [ 1.  1. -1. ...  1. -1. -1.]
 ...
 [-1.  1. -1. ... -1. -1.  1.]
 [-1. -1.  1. ... -1.  1. -1.]
 [-1. -1. -1. ...  1. -1.  1.]]



In [1]:
import os
try:
    from google import colab  # for use in google colab!!    os.system('git clone https://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@github.com/edogariu/meta-opt')
    os.system('pip install -q ./meta-opt')
    os.system('pip install -q dill')
    # !pip install -q jax[cuda12_pip]==0.4.20 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html  # for disabling prealloc, see https://github.com/google/jax/discussions/19014
    os.system('pip install -q tensorflow-text ml_collections clu sentencepiece')  # for WMT
    from google.colab import drive
    drive.mount('/content/drive')
except: pass

from meta_opt.train_loops import train_standard_opt, train_hgd, train_meta_opt
from meta_opt.utils.experiment_utils import make, save_checkpoint, process_results, bcolors, plot, get_final_cparams
from meta_opt import DIR
from meta_opt.workloads.wmt import rsqrt

import re
import matplotlib.pyplot as plt
import numpy as np
import dill as pkl
import optax

project IS NOT JITTED
_compute_control_scalar IS NOT JITTED


In [2]:
# ==================================================
# configuration and seeds for each trial
SEEDS = [7,]

NAME = 'yeet'
CFG = {
    # training options
    'workload': 'CIFAR',
    'num_iters': 10000,
    'eval_every': 100,
    'num_eval_iters': -1,
    'batch_size': 256,
    'full_batch': False,
    'reset_every': 10000,

    # # wmt options
    # 'bleu_every': 5000,
    # 'transformer_size': 'base_short',
    
    # experiment options
    'experiment_name': NAME,
    'load_checkpoint': False,
    'overwrite': True,  # whether to allow us to overwrite existing checkpoints or throw errors
    'directory': f'{DIR}/..',
}

def run(seeds, cfg):
    results = make(cfg)

    processed_results = pkl.load(open('{}/data/ncq_test_processed.pkl'.format(cfg['directory']), 'rb'))
    initial_cparams = get_final_cparams(processed_results, 'cf')
    
    # uncomment the ones to run, with correctly chosen hyperparameters
    for s in seeds:
        CFG['seed'] = s
        print(f'running with seed {s}')
        
        # # ours
        opt = optax.inject_hyperparams(optax.sgd)(learning_rate=2e-4)
        # opt = optax.inject_hyperparams(optax.adam)(learning_rate=1e-3)
        results['cf'].append(train_meta_opt(CFG, counterfactual=True, H=32, HH=2, meta_optimizer=opt))

        # standard benchmarks
        benchmarks = {
            # 'sgd': optax.inject_hyperparams(optax.sgd)(learning_rate=0.4),
            # 'momentum': optax.chain(optax.add_decayed_weights(1e-4), optax.inject_hyperparams(optax.sgd)(learning_rate=0.1, momentum=0.9)),
            # 'adamw': optax.inject_hyperparams(optax.adamw)(learning_rate=1e-3, b1=0.9, b2=0.999, weight_decay=1e-4),
            # 'rmsprop': optax.inject_hyperparams(optax.rmsprop)(learning_rate=1e-3),
            # 'rsqrt': rsqrt(lr=0.004, warmup_steps=4000),
        }
        for k, opt in benchmarks.items(): results[k].append(train_standard_opt(CFG, opt))

        # other
        # results['hgd'].append(train_hgd(CFG, initial_lr=0.1, hypergrad_lr=1e-3))

        save_checkpoint(CFG, results, checkpoint_name=f'seed {s}')
    processed_results = process_results(CFG, results)
# ==================================================

In [3]:
run(SEEDS, CFG)

using cpu for jax
results will be stored at: /Users/evandigiorno/Desktop/meta-opt/notebooks/../data/ncq_pretrained_*.pkl
we will NOT try to load experiment checkpoint first
starting the experiment from scratch :)
running with seed 7
64 params in the model!


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:01<00:00, 520.75it/s, loss=-5.47, eval_loss=-5.47]


64 params in the model!


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:01<00:00, 649.01it/s, loss=-5.51, eval_loss=-5.51, lr=0.4]


64 params in the model!


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:01<00:00, 643.43it/s, loss=-5.5, eval_loss=-5.5, lr=0]


64 params in the model!


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:01<00:00, 625.78it/s, loss=-4.18, eval_loss=-4.18, lr=0.001]


Saved checkpoint seed 7 to /Users/evandigiorno/Desktop/meta-opt/notebooks/../data/ncq_pretrained_raw.pkl
Saved processed results to /Users/evandigiorno/Desktop/meta-opt/notebooks/../data/ncq_pretrained_processed.pkl
